[".editorconfig"]
# top-most EditorConfig file
root = true

[".editorconfig"."*"]
indent_style = "space"
indent_size = 4
insert_final_newline = true
trim_trailing_whitespace = true
end_of_line = "lf"
charset = "utf-8"
max_line_length = 120

[".editorconfig"."*.{yml,yaml,md,toml}"]
indent_size = 2

[".editorconfig".Makefile]
indent_style = "tab"

[".editorconfig"."*.bat"]
indent_style = "tab"
max_line_length = 79
