["setup.cfg".mypy]
allow_redefinition = false
check_untyped_defs = true

disallow_any_explicit = true
pretty = true
show_error_codes = true
disallow_any_generics = true
disallow_untyped_defs = true
disallow_untyped_calls = true
ignore_errors = false
ignore_missing_imports = true
implicit_reexport = false
local_partial_types = true
strict_optional = true
strict_equality = true
no_implicit_optional = true
warn_no_return = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
warn_unreachable = true

[[".pre-commit-config.yaml".repos]]
yaml = """
  -   repo: local
      hooks:
      -   id: mypy
          name: mypy
          language: system
          entry: mypy generator tests
          types: [python]
          pass_filenames: false
"""